[package]
name = "tiny-skia"
version = "0.2.0"
authors = ["Evgeniy Reizner <razrfalcon@gmail.com>"]
edition = "2018"
description = "A tiny Skia subset ported to Rust."
documentation = "https://docs.rs/tiny-skia/"
readme = "README.md"
repository = "https://github.com/RazrFalcon/tiny-skia"
license = "BSD-3-Clause"
keywords = ["2d", "rendering", "skia"]
categories = ["rendering"]

[dependencies]
arrayref = "0.3"
arrayvec = "0.5"
bytemuck = "1.4"
float-cmp = { version = "0.8", default-features = false, features = ["std"] }
num-ext = { git = "https://github.com/RazrFalcon/num-ext", rev = "109f01a" }
png = { version = "0.16", optional = true }
wide = { version = "0.6.2", features = ["std"] }

[features]
default = ["png-format"]

# Allows loading and saving `Pixmap` as PNG.
png-format = ["png"]
