[package]
name = "tiny-skia"
version = "0.2.0"
authors = ["Evgeniy Reizner <razrfalcon@gmail.com>"]
edition = "2018"
description = "A tiny Skia subset ported to Rust."
documentation = "https://docs.rs/tiny-skia/"
readme = "README.md"
repository = "https://github.com/RazrFalcon/tiny-skia"
license = "BSD-3-Clause"
keywords = ["2d", "rendering", "skia"]
categories = ["rendering"]

[dependencies]
arrayref = "0.3.6"
arrayvec = "0.5.1"
bytemuck = "1.4.1"
float-cmp = { version = "0.8", default-features = false, features = ["std"] }
memmap2 = { version = "0.1", optional = true }
num-ext = { git = "https://github.com/RazrFalcon/num-ext", rev = "109f01a" }
png = { version = "0.16.6", optional = true }
safe-geom = { git = "https://github.com/RazrFalcon/checked-geom", rev = "8a96c1b" }
wide = "0.6.1"

[features]
default = ["png-format"]

# Allows loading and saving `Pixmap` as PNG.
png-format = ["png", "memmap2"]
