[package]
name = "skia-rs"
version = "0.1.0"
edition = "2018"

[dependencies]
png = { version = "0.16.6", optional = true }

[build-dependencies]
cc = "1.0"

[features]
default = ["png-encoding"]
png-encoding = ["png"]
