name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        rust:
          - stable
          - 1.36.0
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build without default features
      run: cargo build --no-default-features

    - name: Run tests
      run: cargo test

    - name: Run tests with the target-cpu feature
      run: cargo test --features target-cpu

    - name: Build benches
      run: |
        cd benches
        cargo bench dummy # `cargo build` will not actually build it
        cd ..
